name: 🐛 Reportar bug
description: Algo não está funcionando como deveria
labels: ["bug"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: O que aconteceu?
      description: Descreva o problema de forma simples e direta.
    validations:
      required: true
  - type: textarea
    id: passos
    attributes:
      label: Como chegar nesse erro?
      description: O que você fez pra chegar aqui? Quanto mais detalhes, melhor.
      placeholder: |
        1. Entrei no site
        2. Cliquei em "X"
        3. Apareceu tal mensagem
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: O que deveria ter acontecido?
      description: Qual era a sua expectativa?
    validations:
      required: true
  - type: textarea
    id: captura
    attributes:
      label: Prints ou vídeo (se tiver)
      description: Arraste a imagem aqui ou cole um link. Ajuda muito.
    validations:
      required: false
